#!/usr/bin/env bash
# Idempotent setup for running E2 on a fresh machine (e.g. remote GPU box).
#
# After cloning the repo, run:
#     bash setup.sh
# then:
#     source .venv/bin/activate
#     bash run_e2.sh    (or any of the commands in SETUP.md)
#
# Safe to re-run: each step checks if its work is already done.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

JULIA_VERSION="1.11"        # juliacall 0.9.x requires <= 1.11
PY_MIN_MINOR=10             # need >= 3.10

# ── 1. Julia (juliaup + 1.11) ───────────────────────────────────────────────
if ! command -v juliaup >/dev/null 2>&1; then
    echo "[setup] Installing juliaup (non-interactive)…"
    curl -fsSL https://install.julialang.org | sh -s -- --yes --default-channel "$JULIA_VERSION"
    # juliaup writes to ~/.juliaup; make this shell session aware of it
    export PATH="$HOME/.juliaup/bin:$PATH"
else
    echo "[setup] juliaup already installed."
fi

if ! juliaup status | grep -q "^[ *]\+$JULIA_VERSION"; then
    echo "[setup] Installing Julia $JULIA_VERSION via juliaup…"
    juliaup add "$JULIA_VERSION"
fi

JULIA_BIN="$(juliaup api currentversion 2>/dev/null | awk '{print $2}' || true)"
JULIA_EXE="$(julia +$JULIA_VERSION -e 'print(joinpath(Sys.BINDIR, "julia"))')"
echo "[setup] Using Julia at $JULIA_EXE"

# ── 2. Python venv ──────────────────────────────────────────────────────────
PY_BIN="${PYTHON:-python3}"
PY_MINOR="$($PY_BIN -c 'import sys; print(sys.version_info[1])')"
if [ "$PY_MINOR" -lt "$PY_MIN_MINOR" ]; then
    echo "[setup] ERROR: need Python 3.$PY_MIN_MINOR+, found 3.$PY_MINOR ($PY_BIN)" >&2
    exit 1
fi

if [ ! -d ".venv" ]; then
    echo "[setup] Creating Python venv at .venv …"
    "$PY_BIN" -m venv .venv
fi
# shellcheck disable=SC1091
source .venv/bin/activate
pip install --upgrade pip wheel >/dev/null
pip install -r python/requirements.txt

# ── 3. Julia projects (main + python-bridge runtime) ────────────────────────
echo "[setup] Instantiating main Julia project…"
julia +"$JULIA_VERSION" --project=. -e 'using Pkg; Pkg.instantiate()'

echo "[setup] Instantiating Python-bridge Julia runtime…"
julia +"$JULIA_VERSION" --project=python/julia_runtime \
    -e 'using Pkg; Pkg.instantiate()'

# ── 4. Persist env vars expected by training scripts ────────────────────────
ENV_FILE=".envrc.local"
cat > "$ENV_FILE" <<EOF
# Auto-generated by setup.sh — source this (or let run_e2.sh do it).
export PYTHON_JULIAPKG_OFFLINE=yes
export PYTHON_JULIAPKG_EXE="$JULIA_EXE"
EOF
echo "[setup] Wrote $ENV_FILE — sourced automatically by run_e2.sh."

# ── 5. Smoke test the Python ↔ Julia bridge ─────────────────────────────────
echo "[setup] Running bridge smoke test (one reset+step in E2Env)…"
# shellcheck disable=SC1090
source "$ENV_FILE"
( cd python && python - <<'PY'
from qalibremd_gym.env_e2 import QalibreMDE2Env
env = QalibreMDE2Env(rng_seed=0, simplified_action=True)
obs, _ = env.reset(seed=42)
print(f"obs_dim = {obs.shape[0]}, action_dim = {env.action_space.shape[0]}")
PY
)

echo
echo "[setup] Done. Activate the venv with:  source .venv/bin/activate"
echo "[setup] Then run training with:        bash run_e2.sh"
